import { se2 } from './isslwhatwedo.module.css'
import { sectcontnt } from './isslwhatwedo.module.css'
import { herosectiontext } from './isslwhatwedo.module.css'
import { bodycontainer } from './isslwhatwedo.module.css'
import { btmsd } from './isslwhatwedo.module.css'
import { isslbodyofwork } from './isslwhatwedo.module.css'
import { nomediaquerygrid } from './isslwhatwedo.module.css'
import { autogrid } from './isslwhatwedo.module.css'
import { boxw } from './isslwhatwedo.module.css'
import { imside } from './isslwhatwedo.module.css'
import { txside } from './isslwhatwedo.module.css'
import { txside2} from './isslwhatwedo.module.css'
import { txside3 } from './isslwhatwedo.module.css'
import { rgtarw } from './isslwhatwedo.module.css'
import { nxtscr } from './isslwhatwedo.module.css'
import { splitsecond} from './isslwhatwedo.module.css'
import { topspanner } from './isslwhatwedo.module.css'
import { bottomspanner } from './isslwhatwedo.module.css'
import { imageitall} from './isslwhatwedo.module.css'
import { oursolution} from './isslwhatwedo.module.css'
import { esx } from './isslwhatwedo.module.css'
import { solutionsflex1 } from './isslwhatwedo.module.css'
import {strech1 } from './isslwhatwedo.module.css'
import { ico } from './isslwhatwedo.module.css'
import { hed } from './isslwhatwedo.module.css'
import { tx} from './isslwhatwedo.module.css'
import { strech2 } from './isslwhatwedo.module.css'
import { bpn} from './isslwhatwedo.module.css'
import { box1 } from './isslwhatwedo.module.css'
import { as } from './isslwhatwedo.module.css'
import { bs } from './isslwhatwedo.module.css'
import { ntnt } from './isslwhatwedo.module.css'
import { footersect } from './isslwhatwedo.module.css'
import { startconvo } from './isslwhatwedo.module.css'
import { fs } from './isslwhatwedo.module.css'
import { startconvotxt } from './isslwhatwedo.module.css'
import { startconvobtn } from './isslwhatwedo.module.css'
import { contactusbtn } from './isslwhatwedo.module.css'
import { footergrid } from './isslwhatwedo.module.css'
import { logos } from './isslwhatwedo.module.css'
import { logo } from './isslwhatwedo.module.css'
import { addresssd } from './isslwhatwedo.module.css'
import { addre } from './isslwhatwedo.module.css'
import { tele } from './isslwhatwedo.module.css'
import { mail } from './isslwhatwedo.module.css'
import { linksd } from './isslwhatwedo.module.css'
import { qkl } from './isslwhatwedo.module.css'
import { othlink } from './isslwhatwedo.module.css'
import { inputsd } from './isslwhatwedo.module.css'
import { getupdat } from './isslwhatwedo.module.css'
import { ourproducts } from './isslwhatwedo.module.css'
import { howitall } from './isslwhatwedo.module.css'
import { tpsd } from './isslwhatwedo.module.css'
import { hersec } from './isslwhatwedo.module.css'
import { inptbx } from './isslwhatwedo.module.css'
import { subbtn } from './isslwhatwedo.module.css'

import { paragraph1 } from './isslwhatwedo.module.css'
import { hersec3 } from './isslwhatwedo.module.css'
import { emptys } from './isslwhatwedo.module.css'
import { boxgrid } from './isslwhatwedo.module.css'
import { heas } from './isslwhatwedo.module.css'
import { bod } from './isslwhatwedo.module.css'
import { vision } from './isslwhatwedo.module.css'
import { sss } from './isslwhatwedo.module.css'
import { dddd } from './isslwhatwedo.module.css'
import { sstx } from './isslwhatwedo.module.css'
import { ssbod } from './isslwhatwedo.module.css'
import { ourstorycontent} from './isslwhatwedo.module.css'
import { ima } from './isslwhatwedo.module.css'
import { culturevalues } from './isslwhatwedo.module.css'