import { se2 } from './footernew.module.css'
import { sectcontnt } from './footernew.module.css'
import { herosectiontext } from './footernew.module.css'
import { bodycontainer } from './footernew.module.css'
import { btmsd } from './footernew.module.css'
import { isslbodyofwork } from './footernew.module.css'
import { nomediaquerygrid } from './footernew.module.css'
import { autogrid } from './footernew.module.css'
import { boxw } from './footernew.module.css'
import { imside } from './footernew.module.css'
import { txside } from './footernew.module.css'
import { txside2} from './footernew.module.css'
import { txside3 } from './footernew.module.css'
import { rgtarw } from './footernew.module.css'
import { nxtscr } from './footernew.module.css'
import { splitsecond} from './footernew.module.css'
import { topspanner } from './footernew.module.css'
import { bottomspanner } from './footernew.module.css'
import { imageitall} from './footernew.module.css'
import { oursolution} from './footernew.module.css'
import { esx } from './footernew.module.css'
import { solutionsflex1 } from './footernew.module.css'
import {strech1 } from './footernew.module.css'
import { ico } from './footernew.module.css'
import { hed } from './footernew.module.css'
import { tx} from './footernew.module.css'
import { strech2 } from './footernew.module.css'
import { bpn} from './footernew.module.css'
import { box1 } from './footernew.module.css'
import { as } from './footernew.module.css'
import { bs } from './footernew.module.css'
import { ntnt } from './footernew.module.css'
import { footersect } from './footernew.module.css'
import { startconvo } from './footernew.module.css'
import { fs } from './footernew.module.css'
import { startconvotxt } from './footernew.module.css'
import { startconvobtn } from './footernew.module.css'
import { contactusbtn } from './footernew.module.css'
import { footergrid } from './footernew.module.css'
import { logos } from './footernew.module.css'
import { logo } from './footernew.module.css'
import { addresssd } from './footernew.module.css'
import { addre } from './footernew.module.css'
import { tele } from './footernew.module.css'
import { mail } from './footernew.module.css'
import { linksd } from './footernew.module.css'
import { qkl } from './footernew.module.css'
import { othlink } from './footernew.module.css'
import { inputsd } from './footernew.module.css'
import { getupdat } from './footernew.module.css'
import { ourproducts } from './footernew.module.css'
import { howitall } from './footernew.module.css'
import { tpsd } from './footernew.module.css'
import { hersec } from './footernew.module.css'
import { inptbx } from './footernew.module.css'
import { subbtn } from './footernew.module.css'

import { paragraph1 } from './footernew.module.css'
import { hersec3 } from './footernew.module.css'
import { emptys } from './footernew.module.css'
import { auto_grid } from './footernew.module.css'
import { auto_grid2 } from './footernew.module.css'
import { boxgrid } from './footernew.module.css'
import { heas } from './footernew.module.css'
import { bod } from './footernew.module.css'
import { vision } from './footernew.module.css'
import { sss } from './footernew.module.css'
import { dddd } from './footernew.module.css'
import { sstx } from './footernew.module.css'
import { ssbod } from './footernew.module.css'
import { ourstorycontent} from './footernew.module.css'
import { ima } from './footernew.module.css'
import { culturevalues } from './footernew.module.css'

